version: "3.4"

services:
  <service_name>:
    build:
      context: ./
      dockerfile: Dockerfile-base-image
    ports:
      - "<service_port_main>:8989"
      - "<service_port_debug>:9229" # Debugging port
    restart: on-failure
    entrypoint:
      - ./entrypoint_dev.sh
    environment:
      - "ENVIRONMENT=development"
      - "PORT=8989"
    env_file:
      - .env.development
    volumes:
      - ./:/home/vcita/app:cached
      - /home/vcita/app/node_modules/
