# Edit Group Event Test
# Last updated: 2026-01-23
# Source: tests/scheduling/services/edit_group_event/script.md
# Generated by: Cursor AI exploration with Playwright MCP
# DO NOT EDIT MANUALLY - Regenerate from script.md

import re
from playwright.sync_api import Page, expect


def test_edit_group_event(page: Page, context: dict) -> None:
    """
    Edit an existing group event to modify duration, price, and max attendees.
    
    Prerequisites:
    - User is logged in (from category _setup)
    - Group event exists with created_group_event_id in context (from create_group_event)
    - Browser is on Settings > Services page
    
    Reads from context:
    - created_group_event_id: ID of the group event to edit
    - created_group_event_name: Name of the group event
    
    Saves to context:
    - edited_group_event_duration: New duration in minutes (90)
    - edited_group_event_price: New price (35)
    - edited_group_event_max_attendees: New max attendees (15)
    """
    
    # Verify context has required data from create_group_event
    if "created_group_event_id" not in context:
        raise ValueError("Context missing 'created_group_event_id' - create_group_event test must run first")
    
    if "created_group_event_name" not in context:
        raise ValueError("Context missing 'created_group_event_name' - create_group_event test must run first")
    
    group_event_name = context["created_group_event_name"]
    
    print(f"  Editing group event: {group_event_name}")
    
    # Step 1: Verify on Services page
    print("  Step 1: Verifying on Services page...")
    if "/app/settings/services" not in page.url:
        raise ValueError(f"Expected to be on Services page, but URL is {page.url}")
    
    page.wait_for_selector('iframe[title="angularjs"]', timeout=10000)
    iframe = page.frame_locator('iframe[title="angularjs"]')
    
    # Step 2: Find and click on group event
    print("  Step 2: Opening group event for editing...")
    # HEALED: Services list uses endless scroll - must scroll to find group event
    # Wait for "My Services" text to confirm the list section has loaded
    iframe.get_by_text("My Services").wait_for(state="visible", timeout=10000)
    
    # Scroll multiple times until group event is found or end of list reached
    import re
    max_scrolls = 10
    previous_last_text = ""
    no_change_count = 0
    
    for scroll_attempt in range(max_scrolls):
        # First, try to find the group event - if found, we're done
        # HEALED: Use get_by_text() instead of filter(has_text=...) - filter pattern doesn't work
        try:
            group_event_in_list = iframe.get_by_text(group_event_name)
            if group_event_in_list.count() > 0:
                print(f"  Found group event after {scroll_attempt} scrolls")
                break
        except:
            pass
        
        # Get all service buttons to find the last one
        all_services = iframe.get_by_role("button").filter(has_text=re.compile("Test Consultation|Appointment Test|Free estimate|Another Test|Test Debug|Test Group Workshop|Lawn mowing|On-site|MCP Test|UNIQUE TEST|SCROLL TEST"))
        
        try:
            service_count = all_services.count()
            
            if service_count > 0:
                last_service = all_services.nth(service_count - 1)
                current_last_text = last_service.text_content()
                
                if current_last_text == previous_last_text and previous_last_text != "":
                    no_change_count += 1
                    if no_change_count >= 2:
                        print(f"  Reached end of list after {scroll_attempt + 1} scrolls (no new items)")
                        break
                else:
                    no_change_count = 0
                    previous_last_text = current_last_text
                
                last_service.scroll_into_view_if_needed()
                page.wait_for_timeout(1000)
            else:
                add_button = iframe.get_by_role('button', name='Add 1 on 1 Appointment')
                add_button.scroll_into_view_if_needed()
                page.wait_for_timeout(1000)
        except Exception as e:
            add_button = iframe.get_by_role('button', name='Add 1 on 1 Appointment')
            add_button.scroll_into_view_if_needed()
            page.wait_for_timeout(1000)
    
    # NOW find and click on the group event (all items should be loaded)
    # HEALED: Use get_by_text() instead of filter(has_text=...) - filter pattern doesn't work
    # get_by_text() correctly finds the group event button even when it contains additional text
    group_event_in_list = iframe.get_by_text(group_event_name)
    group_event_in_list.wait_for(state="visible", timeout=10000)
    group_event_in_list.click()
    
    # Step 3: Wait for edit page to load
    page.wait_for_url("**/app/settings/services/**")
    name_field = iframe.get_by_role("textbox", name="Service name *")
    name_field.wait_for(state="visible", timeout=10000)
    
    # Step 4: Change Max Attendees from 10 to 15 (fill is OK for number spinbutton)
    print("  Step 3: Changing max attendees to 15...")
    max_attendees_field = iframe.get_by_role("spinbutton", name="Max attendees icon-q-mark-s *")
    max_attendees_field.click()
    max_attendees_field.fill("15")  # fill is OK for number spinbutton
    
    # Step 5: Change Duration Minutes from 0 to 30
    print("  Step 4: Setting duration to 1 hour 30 minutes...")
    # Click Minutes dropdown
    minutes_dropdown = iframe.get_by_role("listbox", name="Minutes :")
    minutes_dropdown.click()
    # Wait for options to appear
    minutes_option = iframe.get_by_role("option", name="30 Minutes")
    minutes_option.wait_for(state="visible", timeout=5000)
    minutes_option.click()
    
    # Step 6: Change Price from 25 to 35 (fill is OK for number spinbutton)
    print("  Step 5: Changing price to 35...")
    price_field = iframe.get_by_role("spinbutton", name="Service price (ILS) *")
    price_field.click()
    price_field.fill("35")  # fill is OK for number spinbutton
    
    # Step 7: Save Changes
    print("  Step 6: Saving changes...")
    save_btn = iframe.get_by_role("button", name="Save")
    save_btn.click()
    
    # Wait for save to complete - the page refreshes
    name_field = iframe.get_by_role("textbox", name="Service name *")
    name_field.wait_for(state="visible", timeout=10000)
    page.wait_for_timeout(500)  # Brief settle time after save
    
    # Step 8: Verify Changes by Re-checking Field Values
    print("  Step 7: Verifying changes were saved...")
    expect(iframe.get_by_role("spinbutton", name="Max attendees icon-q-mark-s *")).to_have_value("15")
    expect(iframe.get_by_role("listbox", name="Minutes :")).to_contain_text("30 Minutes")
    expect(iframe.get_by_role("spinbutton", name="Service price (ILS) *")).to_have_value("35")
    
    # Step 9: Navigate Back to Services List
    print("  Step 8: Navigating back to services list...")
    settings_menu = page.get_by_text("Settings", exact=True)
    settings_menu.click()
    page.wait_for_url("**/app/settings", timeout=10000)
    
    # Re-acquire iframe reference after navigation
    angular_iframe = page.locator('iframe[title="angularjs"]')
    angular_iframe.wait_for(state="visible", timeout=10000)
    iframe = page.frame_locator('iframe[title="angularjs"]')
    
    # Click Services button
    services_btn = iframe.get_by_role("button", name="Define the services your")
    services_btn.click()
    page.wait_for_url("**/app/settings/services", timeout=10000)
    
    # Wait for services page to load
    services_heading = iframe.get_by_role("heading", name="Settings / Services")
    services_heading.wait_for(state="visible", timeout=15000)
    
    # HEALED 2026-01-27: Replaced page.reload() with UI navigation to comply with navigation rules.
    # After navigating back, navigate away and back to Services to refresh the list.
    # Navigate to Settings main page
    page.get_by_text("Settings", exact=True).click()
    page.wait_for_url("**/app/settings", timeout=10000)
    page.wait_for_selector('iframe[title="angularjs"]', timeout=10000)
    iframe = page.frame_locator('iframe[title="angularjs"]')
    # Navigate back to Services
    services_button = iframe.get_by_role("button", name="Define the services your")
    services_button.wait_for(state="visible", timeout=10000)
    services_button.click()
    page.wait_for_url("**/app/settings/services", timeout=10000)
    
    # Wait for Services heading to confirm page loaded
    services_heading = iframe.get_by_role("heading", name="Settings / Services")
    services_heading.wait_for(state="visible", timeout=10000)
    
    # Wait for "My Services" text to confirm list section loaded
    iframe.get_by_text("My Services").wait_for(state="visible", timeout=10000)
    
    # Step 10: Verify Changes in Services List
    print("  Step 9: Verifying changes in services list...")
    # HEALED: After navigating back, the list may need scrolling to find the group event
    # No arbitrary wait - we wait for "My Services" above, then scroll to find the event
    # Wait for "My Services" text to confirm the list section has loaded
    iframe.get_by_text("My Services").wait_for(state="visible", timeout=10000)
    
    # Scroll multiple times until group event is found or end of list reached
    max_scrolls = 10
    previous_last_text = ""
    no_change_count = 0
    
    for scroll_attempt in range(max_scrolls):
        # First, try to find the group event - if found, we're done
        # HEALED: Use get_by_text() instead of filter(has_text=...) - filter pattern doesn't work
        try:
            group_event_in_list = iframe.get_by_text(group_event_name)
            if group_event_in_list.count() > 0:
                print(f"  Found group event after {scroll_attempt} scrolls")
                break
        except:
            pass
        
        # Get all service buttons to find the last one
        all_services = iframe.get_by_role("button").filter(has_text=re.compile("Test Consultation|Appointment Test|Free estimate|Another Test|Test Debug|Test Group Workshop|Lawn mowing|On-site|MCP Test|UNIQUE TEST|SCROLL TEST"))
        
        try:
            service_count = all_services.count()
            
            if service_count > 0:
                last_service = all_services.nth(service_count - 1)
                current_last_text = last_service.text_content()
                
                if current_last_text == previous_last_text and previous_last_text != "":
                    no_change_count += 1
                    if no_change_count >= 2:
                        print(f"  Reached end of list after {scroll_attempt + 1} scrolls (no new items)")
                        break
                else:
                    no_change_count = 0
                    previous_last_text = current_last_text
                
                last_service.scroll_into_view_if_needed()
                page.wait_for_timeout(1000)
            else:
                add_button = iframe.get_by_role('button', name='Add 1 on 1 Appointment')
                add_button.scroll_into_view_if_needed()
                page.wait_for_timeout(1000)
        except Exception as e:
            add_button = iframe.get_by_role('button', name='Add 1 on 1 Appointment')
            add_button.scroll_into_view_if_needed()
            page.wait_for_timeout(1000)
    
    # Find the group event in the list (all items should be loaded)
    # HEALED: Use get_by_text() instead of filter(has_text=...) - filter pattern doesn't work
    group_event_in_list = iframe.get_by_text(group_event_name)
    group_event_in_list.wait_for(state="visible", timeout=10000)
    
    # HEALED: The services list view does NOT display max attendees in the button text
    # The list only shows the service name, not detailed information like attendee count
    # Changes were already verified in Step 8 by re-checking field values on the edit page
    # Step 10 only verifies that the group event exists in the list after navigation
    
    # Save to context
    context["edited_group_event_duration"] = 90  # 1 hour 30 min = 90 minutes
    context["edited_group_event_price"] = 35
    context["edited_group_event_max_attendees"] = 15
    
    print(f"  [OK] Successfully edited group event: {group_event_name}")
    print(f"     New duration: 90 minutes (1h 30m)")
    print(f"     New price: 35")
    print(f"     New max attendees: 15")
