# Create Group Event Test
# Last updated: 2026-01-23
# Source: tests/scheduling/services/create_group_event/script.md
# Generated by: Cursor AI exploration with Playwright MCP
# DO NOT EDIT MANUALLY - Regenerate from script.md

import re
import time
from playwright.sync_api import Page, expect


def test_create_group_event(page: Page, context: dict) -> None:
    """
    Create a new group event service with name, duration, price, and max attendees.
    Group events differ from 1-on-1 services by allowing multiple participants per time slot.
    
    Prerequisites:
    - User is logged in (from category _setup)
    - Browser is on Settings > Services page (from delete_service test)
    
    Saves to context:
    - created_group_event_id: ID of the created group event
    - created_group_event_name: Name of the group event
    - created_group_event_description: Description of the group event
    - created_group_event_duration: Duration in minutes (60)
    - created_group_event_price: Price of the group event (25)
    - created_group_event_max_attendees: Max attendees (10)
    """
    
    # Step 1: Verify on Services page
    print("  Step 1: Verifying on Services page...")
    if "/app/settings/services" not in page.url:
        raise ValueError(f"Expected to be on Services page, but URL is {page.url}")
    
    page.wait_for_selector('iframe[title="angularjs"]', timeout=10000)
    iframe = page.frame_locator('iframe[title="angularjs"]')
    
    # Generate unique group event name
    timestamp = int(time.time())
    group_event_name = f"Test Group Workshop {timestamp}"
    group_event_description = "Group workshop for testing purposes."
    
    # Step 2: Click New Service dropdown
    print("  Step 2: Opening New service menu...")
    new_service_btn = iframe.get_by_role("button", name="New service icon-caret-down")
    new_service_btn.click()
    
    # Step 3: Wait for dropdown menu to appear
    menu = iframe.get_by_role("menu")
    menu.wait_for(state="visible", timeout=5000)
    
    # Step 4: Select "Group event"
    print("  Step 3: Selecting Group event...")
    group_event_option = iframe.get_by_role("menuitem", name="Group event")
    group_event_option.click()
    
    # Step 5: Wait for dialog to appear
    dialog = iframe.get_by_role("dialog")
    dialog.wait_for(state="visible", timeout=10000)
    
    # Step 6: Fill Service Name (use press_sequentially for text input)
    print(f"  Step 4: Entering service name: {group_event_name}")
    name_field = iframe.get_by_role("textbox", name="Service name *")
    name_field.click()
    page.wait_for_timeout(100)  # Brief delay for field focus
    name_field.press_sequentially(group_event_name, delay=30)
    
    # Step 7: Set Max Attendees (fill is OK for number spinbutton)
    print("  Step 5: Setting max attendees to 10...")
    max_attendees_field = iframe.get_by_role("spinbutton", name="Max attendees icon-q-mark-s *")
    max_attendees_field.click()
    max_attendees_field.fill("10")
    
    # Step 8: Select Location - Face to Face
    print("  Step 6: Selecting Face to face location...")
    face_to_face_btn = iframe.get_by_role("button", name="icon-Home Face to face")
    face_to_face_btn.click()
    
    # Step 9: Wait for address options to appear (radiogroup)
    address_options = iframe.get_by_role("radiogroup")
    address_options.wait_for(state="visible", timeout=5000)
    # Default "My business address" is already selected - no action needed
    
    # Step 10: Select "With fee" and Enter Price
    print("  Step 7: Setting price to 25...")
    with_fee_btn = iframe.get_by_role("button", name="icon-Credit-card With fee")
    with_fee_btn.click()
    
    # Wait for price field to appear
    price_field = iframe.get_by_role("spinbutton", name="Service price *")
    price_field.wait_for(state="visible", timeout=5000)
    price_field.click()
    price_field.fill("25")  # fill is OK for number spinbutton
    
    # Step 11: Click Create
    print("  Step 8: Clicking Create...")
    create_btn = iframe.get_by_role("button", name="Create")
    create_btn.click()
    
    # Step 12: Handle "Enter Event Times" Dialog (CONDITIONAL)
    # This dialog appears only on first group event creation, not always
    # We need to handle both cases: dialog appears OR dialog doesn't appear
    print("  Step 9: Checking for event times dialog...")
    later_btn = iframe.get_by_role("button", name="I'll do it later")
    
    # Wait a short time to see if the dialog appears
    try:
        later_btn.wait_for(state="visible", timeout=3000)
        print("  Step 9a: Event times dialog appeared - dismissing...")
        later_btn.click()
        page.wait_for_timeout(500)  # Brief settle time
    except:
        # Dialog didn't appear - this is OK, continue
        print("  Step 9a: Event times dialog did not appear - continuing...")
    
    # Wait for any remaining dialogs to close
    page.wait_for_timeout(500)  # Brief settle time for dialogs to close
    
    # Step 13: Refresh Services List (Workaround for UI Bug)
    print("  Step 10: Refreshing services list...")
    settings_menu = page.get_by_text("Settings", exact=True)
    settings_menu.click()
    
    # Wait for Settings main page
    page.wait_for_url("**/app/settings", timeout=10000)
    
    # Navigate back to Services
    angular_iframe = page.locator('iframe[title="angularjs"]')
    angular_iframe.wait_for(state="visible", timeout=10000)
    iframe = page.frame_locator('iframe[title="angularjs"]')
    services_btn = iframe.get_by_role("button", name="Define the services your")
    services_btn.click()
    
    # Wait for Services page to load
    page.wait_for_url("**/app/settings/services", timeout=10000)
    services_heading = iframe.get_by_role("heading", name="Settings / Services")
    services_heading.wait_for(state="visible", timeout=10000)
    
    # Step 14: Verify Group Event Created and Get ID
    print("  Step 11: Verifying group event was created...")
    # HEALED: Services list uses endless scroll - must scroll to find group event
    # Wait for "My Services" text to confirm the list section has loaded
    iframe.get_by_text("My Services").wait_for(state="visible", timeout=10000)
    
    # Scroll multiple times until group event is found or end of list reached
    print("  Scrolling to find group event...")
    max_scrolls = 10
    previous_last_text = ""
    no_change_count = 0
    group_event_in_list = None
    
    for scroll_attempt in range(max_scrolls):
        # First, try to find the group event - if found, we're done
        try:
            group_event_in_list = iframe.get_by_role("button").filter(has_text=group_event_name)
            if group_event_in_list.count() > 0:
                print(f"  Found group event after {scroll_attempt} scrolls")
                break
        except:
            pass
        
        # Get all service buttons to find the last one
        all_services = iframe.get_by_role("button").filter(has_text=re.compile("Test Consultation|Appointment Test|Free estimate|Another Test|Test Debug|Test Group Workshop|Lawn mowing|On-site|MCP Test|UNIQUE TEST|SCROLL TEST"))
        
        try:
            service_count = all_services.count()
            
            if service_count > 0:
                last_service = all_services.nth(service_count - 1)
                current_last_text = last_service.text_content()
                
                if current_last_text == previous_last_text and previous_last_text != "":
                    no_change_count += 1
                    if no_change_count >= 2:
                        print(f"  Reached end of list after {scroll_attempt + 1} scrolls")
                        break
                else:
                    no_change_count = 0
                    previous_last_text = current_last_text
                
                last_service.scroll_into_view_if_needed()
                page.wait_for_timeout(1000)
            else:
                add_button = iframe.get_by_role('button', name='Add 1 on 1 Appointment')
                add_button.scroll_into_view_if_needed()
                page.wait_for_timeout(1000)
        except:
            add_button = iframe.get_by_role('button', name='Add 1 on 1 Appointment')
            add_button.scroll_into_view_if_needed()
            page.wait_for_timeout(1000)
    
    # Wait for the group event to appear in the list
    # Group events show "X attendees" instead of "1 on 1"
    group_event_in_list = iframe.get_by_role("button").filter(has_text=group_event_name)
    group_event_in_list.wait_for(state="visible", timeout=10000)
    
    # Verify it shows "10 attendees" (group event indicator)
    expect(group_event_in_list).to_contain_text("10 attendees")
    
    # Click on group event to open advanced edit
    group_event_in_list.click()
    page.wait_for_url("**/app/settings/services/**")
    
    # Wait for advanced edit page to load
    advanced_name_field = iframe.get_by_role("textbox", name="Service name *")
    advanced_name_field.wait_for(state="visible", timeout=10000)
    
    # Get group event ID from URL
    url = page.url
    group_event_id_match = re.search(r'/services/([a-z0-9]+)', url)
    group_event_id = group_event_id_match.group(1) if group_event_id_match else None
    
    print(f"  [OK] Group event created with ID: {group_event_id}")
    
    # Step 15: Add Description (Advanced Edit) - use press_sequentially for text
    print("  Step 12: Adding group event description...")
    description_field = iframe.get_by_role("textbox", name="Service description (optional)")
    description_field.click()
    page.wait_for_timeout(100)  # Brief delay for field focus
    description_field.press_sequentially(group_event_description, delay=20)
    
    # Step 16: Save Advanced Edit
    print("  Step 13: Saving changes...")
    save_btn = iframe.get_by_role("button", name="Save")
    save_btn.click()
    
    # Wait for save to complete - the page refreshes
    advanced_name_field = iframe.get_by_role("textbox", name="Service name *")
    advanced_name_field.wait_for(state="visible", timeout=10000)
    page.wait_for_timeout(500)  # Brief settle time after save
    
    # Step 17: Navigate Back to Services List
    print("  Step 14: Navigating back to services list...")
    settings_menu = page.get_by_text("Settings", exact=True)
    settings_menu.click()
    page.wait_for_url("**/app/settings", timeout=10000)
    
    # Re-acquire iframe reference after navigation
    angular_iframe = page.locator('iframe[title="angularjs"]')
    angular_iframe.wait_for(state="visible", timeout=10000)
    iframe = page.frame_locator('iframe[title="angularjs"]')
    
    # Click Services button to navigate back
    services_btn = iframe.get_by_role("button", name="Define the services your")
    services_btn.click()
    page.wait_for_url("**/app/settings/services", timeout=10000)
    
    # Wait for services page to load
    services_heading = iframe.get_by_role("heading", name="Settings / Services")
    services_heading.wait_for(state="visible", timeout=15000)
    
    # Save to context
    context["created_group_event_id"] = group_event_id
    context["created_group_event_name"] = group_event_name
    context["created_group_event_description"] = group_event_description
    context["created_group_event_duration"] = 60  # 1 hour in minutes
    context["created_group_event_price"] = 25
    context["created_group_event_max_attendees"] = 10
    
    print(f"  [OK] Successfully created group event: {group_event_name}")
    print(f"     Group Event ID: {group_event_id}")
    print(f"     Description: {group_event_description}")
    print(f"     Duration: 60 minutes")
    print(f"     Price: 25")
    print(f"     Max Attendees: 10")
