# Delete Group Event Test
# Last updated: 2026-01-23
# Source: tests/scheduling/services/delete_group_event/script.md
# Generated by: Cursor AI exploration with Playwright MCP
# DO NOT EDIT MANUALLY - Regenerate from script.md

from playwright.sync_api import Page, expect


def test_delete_group_event(page: Page, context: dict) -> None:
    """
    Delete the test group event to clean up test data.
    
    Prerequisites:
    - User is logged in (from category _setup)
    - Group event exists with created_group_event_id in context (from create_group_event)
    - Browser is on Settings > Services page
    
    Reads from context:
    - created_group_event_id: ID of the group event to delete
    - created_group_event_name: Name of the group event
    
    Clears from context:
    - All created_group_event_* and edited_group_event_* variables
    """
    
    # Verify context has required data from create_group_event
    if "created_group_event_id" not in context:
        raise ValueError("Context missing 'created_group_event_id' - create_group_event test must run first")
    
    if "created_group_event_name" not in context:
        raise ValueError("Context missing 'created_group_event_name' - create_group_event test must run first")
    
    group_event_name = context["created_group_event_name"]
    
    print(f"  Deleting group event: {group_event_name}")
    
    # Step 1: Verify on Services page
    print("  Step 1: Verifying on Services page...")
    if "/app/settings/services" not in page.url:
        raise ValueError(f"Expected to be on Services page, but URL is {page.url}")
    
    page.wait_for_selector('iframe[title="angularjs"]', timeout=10000)
    iframe = page.frame_locator('iframe[title="angularjs"]')
    
    # Step 2: Find and click on group event
    print("  Step 2: Opening group event for deletion...")
    group_event_in_list = iframe.get_by_role("button").filter(has_text=group_event_name)
    group_event_in_list.wait_for(state="visible", timeout=10000)
    group_event_in_list.click()
    
    # Step 3: Wait for edit page to load
    page.wait_for_url("**/app/settings/services/**")
    name_field = iframe.get_by_role("textbox", name="Service name *")
    name_field.wait_for(state="visible", timeout=10000)
    
    # Step 4: Click Delete button
    print("  Step 3: Clicking Delete button...")
    delete_btn = iframe.get_by_role("button", name="Delete")
    delete_btn.click()
    
    # Step 5: Wait for confirmation dialog
    dialog = iframe.get_by_role("dialog")
    dialog.wait_for(state="visible", timeout=5000)
    
    # Step 6: Confirm deletion
    print("  Step 4: Confirming deletion...")
    ok_btn = iframe.get_by_role("button", name="Ok")
    ok_btn.click()
    
    # Step 7: Wait for redirect back to services list
    page.wait_for_url("**/app/settings/services", timeout=10000)
    
    # Step 8: Verify group event was deleted
    print("  Step 5: Verifying group event was deleted...")
    services_heading = iframe.get_by_role("heading", name="Settings / Services")
    services_heading.wait_for(state="visible", timeout=10000)
    
    # Verify group event is no longer in the list
    group_event_in_list = iframe.get_by_role("button").filter(has_text=group_event_name)
    expect(group_event_in_list).to_have_count(0)
    
    # Clear all group event context variables
    context.pop("created_group_event_id", None)
    context.pop("created_group_event_name", None)
    context.pop("created_group_event_description", None)
    context.pop("created_group_event_duration", None)
    context.pop("created_group_event_price", None)
    context.pop("created_group_event_max_attendees", None)
    context.pop("edited_group_event_duration", None)
    context.pop("edited_group_event_price", None)
    context.pop("edited_group_event_max_attendees", None)
    
    print(f"  [OK] Successfully deleted group event: {group_event_name}")
