# Edit Contact Test
# Last updated: 2026-01-21
# Source: tests/clients/edit_contact/script.md
# Generated by: Cursor AI exploration with Playwright MCP
# Note: This test edits CONTACT fields (name, address, referred by) - distinct from edit_matter which edits PROPERTY fields

import re
import time
from playwright.sync_api import Page, expect


def generate_edit_data() -> dict:
    """Generate new values for editing contact fields."""
    timestamp = int(time.time())
    
    return {
        "last_name": f"ContactEdit{timestamp}",
        "address": f"EDITED: {timestamp % 1000} Updated Street, New City",
        "referred_by": f"EDITED: Test Referral - {timestamp}",
    }


def test_edit_contact(page: Page, context: dict) -> None:
    """
    Test: Edit Contact Information
    
    Edits contact fields (Last Name, Address, Referred by) of an existing matter
    and verifies the changes are saved.
    This test runs AFTER edit_matter and BEFORE delete_matter.
    
    Reads from context:
    - created_matter_id: The ID of the matter to edit
    - created_matter_name: The current full name (for extracting first name)
    
    Saves to context:
    - edited_last_name: The new last name value
    - edited_address: The new address value
    - edited_referred_by: The new referred by value
    - created_matter_name: Updated to new full name
    """
    # Verify context has required data from create_matter
    if "created_matter_id" not in context:
        raise ValueError("Context missing 'created_matter_id' - create_matter test must run first")
    
    if "created_matter_name" not in context:
        raise ValueError("Context missing 'created_matter_name' - create_matter test must run first")
    
    matter_id = context["created_matter_id"]
    current_name = context["created_matter_name"]
    
    # Extract first name from current full name (assumes "FirstName LastName" format)
    first_name = current_name.split()[0] if current_name else "Unknown"
    
    print(f"  Editing contact for: {current_name} (ID: {matter_id})")
    
    # Generate new values for editing
    edit_data = generate_edit_data()
    
    # ========== STEP 1: Navigate to Matter Detail Page ==========
    
    print("  Step 1: Navigating to matter detail page...")
    # Navigate to matter detail page if not already there
    if matter_id not in page.url:
        page.goto(f"https://app.vcita.com/app/clients/{matter_id}")
        page.wait_for_load_state("domcontentloaded")
        page.wait_for_timeout(2000)
    
    # Verify on correct page
    expect(page).to_have_url(re.compile(rf"/app/clients/{re.escape(matter_id)}"))
    
    # ========== STEP 2: Wait for Page and Iframes to Load ==========
    
    print("  Step 2: Waiting for iframes to load...")
    # Wait for outer iframe
    page.wait_for_selector('iframe[title="angularjs"]', timeout=15000)
    page.wait_for_timeout(2000)  # Extra wait for iframe content
    
    # Get nested iframe structure
    outer_iframe = page.frame_locator('iframe[title="angularjs"]')
    inner_iframe = outer_iframe.frame_locator('#vue_iframe_layout')
    
    # ========== STEP 3: Open Edit Contact Dialog ==========
    
    print("  Step 3: Opening edit contact dialog...")
    # Click edit contact button
    # VERIFIED PLAYWRIGHT CODE from MCP:
    edit_contact_button = inner_iframe.locator('.contact-header > .v-icon.notranslate.edit-button')
    edit_contact_button.wait_for(state="visible", timeout=10000)
    edit_contact_button.click()
    
    # Wait for edit dialog to appear
    outer_iframe.locator("text=Edit contact info").wait_for(timeout=10000)
    page.wait_for_timeout(500)  # Wait for dialog animation
    
    # ========== STEP 4: Edit Last Name Field ==========
    
    print(f"  Step 4: Editing Last Name to '{edit_data['last_name']}'...")
    # VERIFIED PLAYWRIGHT CODE from MCP:
    last_name_field = outer_iframe.get_by_role("textbox", name="Last Name")
    last_name_field.click()
    page.keyboard.press("Control+a")  # Select all existing text
    last_name_field.press_sequentially(edit_data["last_name"], delay=30)
    
    # ========== STEP 5: Edit Address Field ==========
    
    print(f"  Step 5: Editing Address to '{edit_data['address']}'...")
    # VERIFIED PLAYWRIGHT CODE from MCP:
    # Note: has Google Places autocomplete, clicking another field dismisses it
    address_field = outer_iframe.get_by_role("textbox", name="Address")
    address_field.click()
    page.keyboard.press("Control+a")  # Select all
    address_field.press_sequentially(edit_data["address"], delay=30)
    
    # ========== STEP 6: Edit Referred By Field ==========
    
    print(f"  Step 6: Editing Referred by to '{edit_data['referred_by']}'...")
    # VERIFIED PLAYWRIGHT CODE from MCP:
    # Clicking this also dismisses address autocomplete dropdown
    referred_field = outer_iframe.get_by_role("textbox", name="Referred by")
    referred_field.click()  # This also dismisses address autocomplete dropdown
    page.keyboard.press("Control+a")  # Select all
    referred_field.press_sequentially(edit_data["referred_by"], delay=30)
    
    # ========== STEP 7: Save Changes ==========
    
    print("  Step 7: Saving changes...")
    # VERIFIED PLAYWRIGHT CODE from MCP:
    save_button = outer_iframe.get_by_role("button", name="Save")
    save_button.click()
    
    # Wait for dialog to close and page to update
    page.wait_for_timeout(2000)
    
    # ========== STEP 8: Verify Changes - Check Page Title ==========
    
    print("  Step 8: Verifying page title updated...")
    # VERIFIED PLAYWRIGHT CODE from MCP:
    # Page title format: "Property / {First Name} {Last Name} | vcita"
    expected_name = f"{first_name} {edit_data['last_name']}"
    expect(page).to_have_title(re.compile(re.escape(expected_name)), timeout=10000)
    
    # ========== STEP 9: Verify Changes - Re-open Dialog and Check Fields ==========
    
    print("  Step 9: Re-opening dialog to verify field values...")
    # VERIFIED PLAYWRIGHT CODE from MCP:
    # Re-open edit dialog to verify values
    edit_contact_button.click()
    outer_iframe.locator("text=Edit contact info").wait_for(timeout=10000)
    page.wait_for_timeout(500)
    
    # Verify Last Name
    expect(outer_iframe.get_by_role("textbox", name="Last Name")).to_have_value(edit_data["last_name"], timeout=5000)
    
    # Verify Address
    expect(outer_iframe.get_by_role("textbox", name="Address")).to_have_value(edit_data["address"], timeout=5000)
    
    # Verify Referred by
    expect(outer_iframe.get_by_role("textbox", name="Referred by")).to_have_value(edit_data["referred_by"], timeout=5000)
    
    # Close dialog
    outer_iframe.get_by_role("button", name="Cancel").click()
    page.wait_for_timeout(500)
    
    # ========== Update Context ==========
    
    # Save edited values to context
    context["edited_last_name"] = edit_data["last_name"]
    context["edited_address"] = edit_data["address"]
    context["edited_referred_by"] = edit_data["referred_by"]
    
    # Update the matter name in context with new last name
    new_full_name = f"{first_name} {edit_data['last_name']}"
    context["created_matter_name"] = new_full_name
    
    print(f"  [OK] Successfully edited contact: {new_full_name}")
    print(f"     New last name: {edit_data['last_name']}")
    print(f"     New address: {edit_data['address']}")
    print(f"     New referred by: {edit_data['referred_by']}")


# For standalone testing
if __name__ == "__main__":
    from playwright.sync_api import sync_playwright
    import sys
    import os
    
    # Add project root to path
    project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
    sys.path.insert(0, project_root)
    
    # Import login and create_matter functions
    from tests._functions.login.test import fn_login
    from tests.clients.create_matter.test import test_create_matter
    from tests.clients.edit_matter.test import test_edit_matter
    
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        browser_context = browser.new_context()
        page = browser_context.new_page()
        context = {}
        
        try:
            # Login first
            print("Logging in...")
            fn_login(page, context, username="itzik+autotest@vcita.com", password="vcita123")
            print("Login successful!")
            
            # Create a matter first
            print("\nCreating a matter first...")
            test_create_matter(page, context)
            print("Matter created!")
            
            # Edit matter fields
            print("\nEditing matter fields...")
            test_edit_matter(page, context)
            print("Matter edited!")
            
            # Run the edit contact test
            print("\nEditing contact fields...")
            test_edit_contact(page, context)
            print("\n[OK] Test passed!")
            print(f"\nContext after edit_contact:")
            print(f"  - created_matter_name: {context.get('created_matter_name')}")
            print(f"  - edited_last_name: {context.get('edited_last_name')}")
            print(f"  - edited_address: {context.get('edited_address')}")
            print(f"  - edited_referred_by: {context.get('edited_referred_by')}")
            
            # Keep browser open for inspection
            input("\nPress Enter to close browser...")
            
        except Exception as e:
            print(f"\n[FAIL] Test failed: {e}")
            page.screenshot(path="edit_contact_error.png")
            raise
        finally:
            browser.close()
