# Edit Matter Test
# Last updated: 2026-04-05
# Source: tests/clients/edit_matter/steps.md
# Generated by: Cursor AI exploration with Playwright MCP
# Note: "Matter" is vcita's general entity - called "Property" for Home Services, "Client" for generic, etc.

import re
import time
from playwright.sync_api import Page, expect

from tests._params import MATTER_ENTITY_NAMES

_ENTITY_PATTERN = "|".join([e.capitalize() for e in MATTER_ENTITY_NAMES])
EDIT_DIALOG_TITLE_RE = re.compile(
    rf"Edit\s+({_ENTITY_PATTERN.lower()}|{_ENTITY_PATTERN})\s+info", re.IGNORECASE
)


def generate_edit_data() -> dict:
    timestamp = int(time.time())
    return {
        "tag": f"auto-test-{timestamp % 100000}",
        "help_request": f"EDITED: Need updated services - {timestamp}",
        "special_instructions": f"EDITED: New gate code is 9999. Updated on {timestamp}",
    }


def _find_edit_dialog_title(outer_iframe, timeout_ms: int = 15000):
    """Wait for the edit dialog to appear, matching any entity name."""
    for entity in MATTER_ENTITY_NAMES:
        title_text = f"Edit {entity} info"
        loc = outer_iframe.locator(f"text={title_text}")
        try:
            loc.wait_for(state="visible", timeout=2000)
            return loc, entity
        except Exception:
            continue
    loc = outer_iframe.locator("text=/Edit .+ info/i")
    loc.wait_for(state="visible", timeout=max(0, timeout_ms - len(MATTER_ENTITY_NAMES) * 2000))
    return loc, "unknown"


def test_edit_matter(page: Page, context: dict) -> None:
    """
    Test: Edit Matter Fields

    Edits an existing matter by modifying available fields and verifying changes.
    Adapts to both Property form (help request, special instructions) and
    Client form (tags).

    Reads from context:
    - created_matter_name, created_matter_id

    Saves to context:
    - edited_tag or edited_help_request / edited_special_instructions
    """
    if "created_matter_id" not in context:
        raise ValueError("Context missing 'created_matter_id' - create_matter test must run first")
    if "created_matter_name" not in context:
        raise ValueError("Context missing 'created_matter_name' - create_matter test must run first")

    matter_id = context["created_matter_id"]
    matter_name = context["created_matter_name"]
    edit_data = generate_edit_data()

    print(f"  Editing matter: {matter_name} (ID: {matter_id})")

    # ========== PART 1: Verify on matter detail page ==========
    print("  Step 1: Navigating to matter detail page...")
    if matter_id not in page.url:
        raise ValueError(
            f"Expected to be on matter page {matter_id}, but URL is {page.url}. "
            "Sequential test context violation."
        )
    expect(page).to_have_url(re.compile(rf"/app/clients/{re.escape(matter_id)}"))

    print("  Step 2: Waiting for page to load...")
    expect(page).to_have_title(re.compile(re.escape(matter_name)), timeout=15000)

    # ========== PART 2: Open edit dialog ==========
    print("  Step 3: Opening edit dialog...")
    angular_iframe = page.locator('iframe[title="angularjs"]')
    angular_iframe.wait_for(state="visible", timeout=15000)

    outer_iframe = page.frame_locator('iframe[title="angularjs"]')
    inner_iframe = outer_iframe.frame_locator('#vue_iframe_layout')

    inner_iframe.get_by_role("button", name=matter_name).first.wait_for(timeout=15000)

    edit_button = inner_iframe.get_by_role("button").nth(2)
    edit_button.wait_for(state="visible", timeout=10000)
    edit_button.click()

    print("  Step 4: Waiting for edit dialog...")
    dialog_title_loc, entity_type = _find_edit_dialog_title(outer_iframe)
    print(f"  [OK] Edit dialog opened (entity: {entity_type})")
    page.wait_for_timeout(300)

    # ========== PART 3: Edit fields based on what's available ==========
    edited_fields = {}

    help_field = outer_iframe.get_by_role("textbox", name="How can we help you?")
    has_help_field = False
    try:
        has_help_field = help_field.count() > 0
    except Exception:
        pass

    if has_help_field:
        print("  Step 5: Editing property-specific fields...")
        help_field.click()
        help_field.fill("")
        help_field.press_sequentially(edit_data["help_request"], delay=20)
        edited_fields["help_request"] = edit_data["help_request"]

        instructions_field = outer_iframe.get_by_role(
            "textbox", name="Special instructions/requests"
        )
        try:
            if instructions_field.count() > 0:
                instructions_field.click()
                instructions_field.fill("")
                instructions_field.press_sequentially(
                    edit_data["special_instructions"], delay=20
                )
                edited_fields["special_instructions"] = edit_data["special_instructions"]
        except Exception:
            pass
    else:
        print("  Step 5: Editing client-level fields (tags)...")
        tags_input = outer_iframe.locator('input[placeholder="Add tags"]')
        try:
            if tags_input.count() == 0:
                tags_input = outer_iframe.get_by_label("Add tags")
        except Exception:
            pass

        try:
            if tags_input.count() > 0:
                tags_input.click()
                tags_input.press_sequentially(edit_data["tag"], delay=30)
                tags_input.press("Enter")
                page.wait_for_timeout(300)
                edited_fields["tag"] = edit_data["tag"]
                print(f"  [OK] Added tag: {edit_data['tag']}")
        except Exception as e:
            print(f"  [WARN] Could not add tag: {e}")

    # ========== PART 4: Save ==========
    print("  Step 6: Saving changes...")
    save_button = outer_iframe.get_by_role("button", name=re.compile(r"Save|SAVE", re.IGNORECASE))
    save_button.click()

    dialog_title_loc.wait_for(state="hidden", timeout=15000)
    edit_button.wait_for(state="visible", timeout=10000)
    print("  [OK] Dialog closed, changes saved")

    # ========== PART 5: Verify ==========
    if has_help_field and "help_request" in edited_fields:
        print("  Step 7: Verifying changes (reopening dialog)...")
        edit_button.click()
        dialog_verify, _ = _find_edit_dialog_title(outer_iframe)
        page.wait_for_timeout(300)

        help_verify = outer_iframe.get_by_role("textbox", name="How can we help you?")
        expect(help_verify).to_have_value(edited_fields["help_request"], timeout=5000)

        if "special_instructions" in edited_fields:
            instr_verify = outer_iframe.get_by_role(
                "textbox", name="Special instructions/requests"
            )
            expect(instr_verify).to_have_value(
                edited_fields["special_instructions"], timeout=5000
            )

        cancel_button = outer_iframe.get_by_role("button", name="Cancel")
        cancel_button.click()
        dialog_verify.wait_for(state="hidden", timeout=10000)
    elif "tag" in edited_fields:
        print("  Step 7: Verifying tag was saved (reopening dialog)...")
        edit_button.click()
        dialog_verify, _ = _find_edit_dialog_title(outer_iframe)
        page.wait_for_timeout(500)

        tag_text = outer_iframe.locator(f"text={edited_fields['tag']}")
        try:
            tag_text.wait_for(state="visible", timeout=5000)
            print(f"  [OK] Tag '{edited_fields['tag']}' verified in dialog")
        except Exception:
            print(f"  [WARN] Could not verify tag in dialog, continuing")

        cancel_button = outer_iframe.get_by_role(
            "button", name=re.compile(r"Cancel|CANCEL", re.IGNORECASE)
        )
        cancel_button.click()
        dialog_verify.wait_for(state="hidden", timeout=10000)

    for key, val in edited_fields.items():
        context[f"edited_{key}"] = val

    print(f"  [OK] Successfully edited matter: {matter_name}")
    for key, val in edited_fields.items():
        print(f"     {key}: {val[:50]}{'...' if len(val) > 50 else ''}")
