{{- range $job := .Values.jobs }}
{{- if $job.serviceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $job.serviceAccount.name }}
  {{- if $job.serviceAccount.iamRole }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $job.serviceAccount.iamRole }}
  {{- end }}
{{- end }}
{{- end }}
