# Auto-generated from script.md
# Last updated: 2026-01-21
# Source: tests/clients/delete_matter/script.md
# Generated by: Cursor AI exploration with Playwright MCP
# Note: "Matter" is vcita's general entity - called "Property" for Home Services, "Patient" for Healthcare, etc.

import re
from playwright.sync_api import Page, expect


def test_delete_matter(page: Page, context: dict) -> None:
    """
    Test: Delete Matter from Clients List
    
    Deletes an existing matter from the clients/properties list
    and verifies the deletion was successful.
    
    Requires context from create_matter test:
    - created_matter_name: The full name of the matter to delete
    - created_matter_email: The email (optional, for verification)
    - created_matter_id: The ID (optional, for verification)
    
    Clears from context after successful deletion:
    - created_matter_name
    - created_matter_email
    - created_matter_id
    """
    # Verify context has required data
    matter_name = context.get("created_matter_name")
    if not matter_name:
        raise ValueError("Context missing 'created_matter_name' - run create_matter test first")
    
    print(f"  Deleting matter: {matter_name}")
    
    # ========== PART 1: Navigate to Clients/Properties List ==========
    
    # Step 1: Click Properties/Clients in Sidebar
    # Note: This account uses "Properties" terminology (Home Services vertical)
    properties_nav = page.locator('.menu-items-group > div:nth-child(4)')
    properties_nav.click()
    
    # Wait for navigation and table to load
    # NOTE: Don't use networkidle - vcita has continuous background requests
    page.wait_for_url(re.compile(r"/app/clients"), timeout=10000)
    page.wait_for_load_state("domcontentloaded")
    
    # ========== PART 2: Find and Select the Matter ==========
    
    # Step 2: Search for the matter so it appears on the first page (list is paginated)
    # HEALED: Without search, the matter may be on page 2+ (e.g. 116 properties, 6 pages) and row lookup times out
    searchbox = page.get_by_role("searchbox", name="Search by name, email, or phone number")
    searchbox.fill(matter_name)
    # Wait for list to filter and matter row to be visible
    matter_row = page.get_by_role("row", name=matter_name)
    matter_row.wait_for(state="visible", timeout=10000)
    
    # Step 4: Select the matter via the row's checkbox
    # HEALED 2026-01-26: Checkbox is wrapped in a button and may not be directly clickable; click the wrapping button.
    # Use ancestor button so we don't depend on button order (e.g. .first can be a different control on Properties).
    matter_row.get_by_role("checkbox").locator("xpath=ancestor::button[1]").click()
    
    # Verify selection indicator appears (entity label varies by vertical: PROPERTIES, CLIENTS, PATIENTS)
    # HEALED: Was r"1 SELECTED OF \d+ PROPERTIES" - failed when vertical uses "CLIENTS" (e.g. non–Home Services)
    selection_indicator = page.get_by_text(re.compile(r"1 SELECTED OF \d+"))
    selection_indicator.wait_for(state="visible", timeout=10000)
    
    # ========== PART 3: Delete the Matter ==========
    
    # Step 5: Click the More button
    more_btn = page.get_by_role("button", name="More", exact=True)
    more_btn.click()
    
    # Wait for dropdown menu to appear
    delete_option = page.locator('div').filter(has_text=re.compile(r"^Delete$")).nth(1)
    delete_option.wait_for(state="visible", timeout=5000)
    
    # Step 6: Click Delete option in the dropdown
    delete_option.click()
    
    # Wait for confirmation dialog (title varies by vertical: "Delete properties?", "Delete clients?", etc.)
    # Entity-agnostic: match "Delete <entity>?" so test works across clients, properties, patients, students, pets
    dialog_title = page.get_by_text(re.compile(r"Delete .+\?", re.IGNORECASE))
    dialog_title.wait_for(state="visible", timeout=5000)
    
    # Step 7: Confirm deletion by clicking Delete in the dialog
    confirm_delete_btn = page.get_by_role("button", name="Delete")
    confirm_delete_btn.click()
    
    # Wait for success dialog (title varies: "Properties deleted", "Clients deleted", etc.)
    # Match only matter-entity success (not "Note deleted successfully" from Notes subcategory).
    success_dialog_title = page.get_by_text(re.compile(r"(properties|clients|patients|students|pets)\s+deleted", re.IGNORECASE))
    success_dialog_title.wait_for(state="visible", timeout=10000)
    
    # Step 8: Acknowledge success dialog
    # Click OK to dismiss the success dialog
    ok_btn = page.get_by_role("button", name="OK")
    ok_btn.click()
    
    # Wait for dialog to close
    success_dialog_title.wait_for(state="hidden", timeout=10000)
    
    # ========== PART 4: Verify Deletion (USER PERSPECTIVE) ==========
    # CRITICAL: We verify the ACTUAL RESULT, not just the success message
    
    # Step 9: Verify the matter is ACTUALLY no longer in the list
    # This is the PRIMARY validation - the user would check if the item is gone
    matter_row_after = page.get_by_role("row", name=matter_name)
    expect(matter_row_after).to_have_count(0, timeout=10000)
    
    # Step 10: Clear context data
    context.pop("created_matter_name", None)
    context.pop("created_matter_email", None)
    context.pop("created_matter_id", None)
    
    print(f"  [OK] Successfully deleted matter: {matter_name}")
    print(f"     Context cleared: created_matter_name, created_matter_email, created_matter_id")
