# Auto-generated from script.md
# Last updated: 2026-01-21
# Source: tests/clients/delete_matter/script.md
# Generated by: Cursor AI exploration with Playwright MCP
# Note: "Matter" is vcita's general entity - called "Property" for Home Services, "Patient" for Healthcare, etc.

import re
from playwright.sync_api import Page, expect


def test_delete_matter(page: Page, context: dict) -> None:
    """
    Test: Delete Matter from Clients List
    
    Deletes an existing matter from the clients/properties list
    and verifies the deletion was successful.
    
    Requires context from create_matter test:
    - created_matter_name: The full name of the matter to delete
    - created_matter_email: The email (optional, for verification)
    - created_matter_id: The ID (optional, for verification)
    
    Clears from context after successful deletion:
    - created_matter_name
    - created_matter_email
    - created_matter_id
    """
    # Verify context has required data
    matter_name = context.get("created_matter_name")
    if not matter_name:
        raise ValueError("Context missing 'created_matter_name' - run create_matter test first")
    
    print(f"  Deleting matter: {matter_name}")
    
    # ========== PART 1: Navigate to Clients/Properties List ==========
    
    # Step 1: Click Properties/Clients in Sidebar
    # Note: This account uses "Properties" terminology (Home Services vertical)
    properties_nav = page.locator('.menu-items-group > div:nth-child(4)')
    properties_nav.click()
    
    # Wait for navigation and table to load
    # NOTE: Don't use networkidle - vcita has continuous background requests
    page.wait_for_url(re.compile(r"/app/clients"), timeout=10000)
    page.wait_for_load_state("domcontentloaded")
    page.wait_for_timeout(2000)  # Wait for table to render
    
    # ========== PART 2: Find and Select the Matter ==========
    
    # Step 2: Locate the matter row in the table
    matter_row = page.get_by_role("row", name=matter_name)
    expect(matter_row).to_be_visible(timeout=10000)
    
    # Step 3: Click the checkbox button in the matter's row
    # Note: The checkbox is wrapped in a button element due to UI framework
    checkbox_btn = matter_row.get_by_role("button").first
    checkbox_btn.click()
    
    # Wait for selection to register
    page.wait_for_timeout(500)
    
    # Verify selection indicator appears
    selection_indicator = page.get_by_text(re.compile(r"1 SELECTED OF \d+ PROPERTIES"))
    expect(selection_indicator).to_be_visible(timeout=5000)
    
    # ========== PART 3: Delete the Matter ==========
    
    # Step 4: Click the More button
    more_btn = page.get_by_role("button", name="More", exact=True)
    more_btn.click()
    
    # Wait for dropdown menu
    page.wait_for_timeout(300)
    
    # Step 5: Click Delete option in the dropdown
    # The Delete option is under the MANAGE section
    delete_option = page.locator('div').filter(has_text=re.compile(r"^Delete$")).nth(1)
    delete_option.click()
    
    # Wait for confirmation dialog
    page.wait_for_timeout(500)
    
    # Verify confirmation dialog appeared
    dialog_title = page.get_by_text("Delete properties?")
    expect(dialog_title).to_be_visible(timeout=5000)
    
    # Step 6: Confirm deletion by clicking Delete in the dialog
    confirm_delete_btn = page.get_by_role("button", name="Delete")
    confirm_delete_btn.click()
    
    # Wait for success dialog to appear
    page.wait_for_timeout(500)
    
    # Step 7: Acknowledge success dialog
    # Dialog shows: "Properties deleted" with message about waiting for list update
    success_dialog_title = page.get_by_text("Properties deleted")
    expect(success_dialog_title).to_be_visible(timeout=5000)
    
    # Click OK to dismiss the success dialog
    ok_btn = page.get_by_role("button", name="OK")
    ok_btn.click()
    
    # Wait for dialog to close and table to refresh
    page.wait_for_timeout(2000)  # As the dialog suggests, wait for list to update
    
    # ========== PART 4: Verify Deletion (USER PERSPECTIVE) ==========
    # CRITICAL: We verify the ACTUAL RESULT, not just the success message
    
    # Step 8: Verify the matter is ACTUALLY no longer in the list
    # This is the PRIMARY validation - the user would check if the item is gone
    matter_row_after = page.get_by_role("row", name=matter_name)
    expect(matter_row_after).to_have_count(0, timeout=10000)
    
    # Step 8: Clear context data
    context.pop("created_matter_name", None)
    context.pop("created_matter_email", None)
    context.pop("created_matter_id", None)
    
    print(f"  [OK] Successfully deleted matter: {matter_name}")
    print(f"     Context cleared: created_matter_name, created_matter_email, created_matter_id")


# For standalone testing
if __name__ == "__main__":
    from playwright.sync_api import sync_playwright
    import sys
    import os
    
    # Add project root to path
    project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
    sys.path.insert(0, project_root)
    
    # Import functions
    from tests._functions.login.test import fn_login
    from tests.clients.create_matter.test import test_create_matter
    
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        browser_context = browser.new_context()
        page = browser_context.new_page()
        context = {}
        
        try:
            # Login first
            print("Step 1: Logging in...")
            fn_login(page, context, username="itzik+autotest@vcita.com", password="vcita123")
            print("Login successful!")
            
            # Create a matter first (so we have something to delete)
            print("\nStep 2: Creating a matter to delete...")
            test_create_matter(page, context)
            print(f"Created matter: {context.get('created_matter_name')}")
            
            # Delete the matter
            print("\nStep 3: Deleting the matter...")
            test_delete_matter(page, context)
            print("\n✅ Delete test passed!")
            
            # Verify context is cleared
            print(f"\nContext after deletion:")
            print(f"  - created_matter_name: {context.get('created_matter_name', 'CLEARED')}")
            print(f"  - created_matter_email: {context.get('created_matter_email', 'CLEARED')}")
            print(f"  - created_matter_id: {context.get('created_matter_id', 'CLEARED')}")
            
            # Keep browser open for inspection
            input("\nPress Enter to close browser...")
            
        except Exception as e:
            print(f"\n❌ Test failed: {e}")
            page.screenshot(path="delete_matter_error.png")
            raise
        finally:
            browser.close()
