# Auto-generated from script.md
# Last updated: 2026-04-05
# Source: tests/clients/create_matter/script.md
# Generated by: Cursor AI exploration with Playwright MCP
# Note: "Matter" is vcita's general entity - called "Property" for Home Services, "Client" for generic, etc.

import re
import time
import random
from playwright.sync_api import Page, expect

from tests._functions._config import get_base_url
from tests._params import ADD_MATTER_TEXT_REGEX, MATTER_ENTITY_NAMES


def generate_test_data() -> dict:
    """Generate random test data for matter creation.
    Uses short suffix (6 digits) so displayed name fits in table without ellipsis."""
    timestamp = int(time.time())
    first_name = random.choice(["Test", "John", "Jane", "Alex", "Sam"])
    last_name = f"Matter{timestamp % 1000000}"
    email = f"test_{timestamp}@vcita-test.com"
    phone = f"555{random.randint(1000000, 9999999)}"
    contact_address = f"{random.randint(100, 999)} Test Street, Test City"
    matter_address = f"{random.randint(100, 999)} Property Lane, Property Town"
    matter_type = random.choice(["Residential", "Commercial"])
    help_request = "Looking for regular lawn maintenance and landscaping services"
    special_instructions = f"Please call before arriving. Gate code: {random.randint(1000, 9999)}"
    private_notes = f"VIP customer - Test automation record. Created: {timestamp}"
    referred_by = random.choice(["Google Search", "Facebook", "Friend Referral", "Website"])

    return {
        "first_name": first_name,
        "last_name": last_name,
        "full_name": f"{first_name} {last_name}",
        "email": email,
        "phone": phone,
        "contact_address": contact_address,
        "matter_address": matter_address,
        "matter_type": matter_type,
        "help_request": help_request,
        "special_instructions": special_instructions,
        "private_notes": private_notes,
        "referred_by": referred_by,
    }


def _open_add_matter_via_dashboard_panel(page: Page) -> bool:
    """Try to open the Add matter form via the dashboard 'Quick actions' panel.
    Returns True if successfully clicked, False if panel not found."""
    try:
        quick_section = page.get_by_text("Quick actions", exact=True)
        quick_section.wait_for(state="visible", timeout=8000)
        quick_section = quick_section.locator("../..")
        add_matter_locator = quick_section.get_by_text(ADD_MATTER_TEXT_REGEX)
        add_matter_locator.wait_for(state="visible", timeout=5000)
        page.wait_for_timeout(2500)
        add_matter_clickable = add_matter_locator.locator("..")
        add_matter_clickable.scroll_into_view_if_needed()
        page.wait_for_timeout(300)
        add_matter_clickable.click()
        return True
    except Exception:
        return False


def _open_add_matter_via_sidebar(page: Page) -> None:
    """Open the Add matter form via the sidebar Quick Actions button.
    This is the fallback when the dashboard panel doesn't load."""
    sidebar_btn = page.get_by_role("button", name="Quick Actions")
    sidebar_btn.wait_for(state="visible", timeout=15000)
    sidebar_btn.click()
    page.wait_for_timeout(1500)

    add_btn = page.get_by_text(ADD_MATTER_TEXT_REGEX).first
    add_btn.wait_for(state="visible", timeout=10000)
    add_btn.click()


def _find_form_frame(page: Page, timeout_ms: int = 30000):
    """Wait for the 'First Name' field to appear in any frame and return that frame."""
    deadline = time.time() + timeout_ms / 1000
    while time.time() < deadline:
        for frame in page.frames:
            try:
                if frame.locator('text=First Name').count() > 0:
                    frame.locator('text=First Name').wait_for(state='visible', timeout=500)
                    return frame
            except Exception:
                continue
        page.wait_for_timeout(500)
    return None


def _try_fill_field(form_frame, role: str, name: str, value: str, use_press: bool = True) -> bool:
    """Try to fill a field if it exists. Returns True if filled, False if not found."""
    try:
        field = form_frame.get_by_role(role, name=name)
        if field.count() == 0:
            return False
        field.click()
        if use_press:
            field.press_sequentially(value, delay=30)
        else:
            field.fill(value)
        return True
    except Exception:
        return False


def _try_fill_combobox(form_frame, page: Page, textbox_name: str, combobox_name: str, value: str) -> bool:
    """Try to fill a combobox field (click textbox first, then type into combobox)."""
    try:
        field = form_frame.get_by_role("textbox", name=textbox_name)
        if field.count() == 0:
            return False
        field.click()
        page.wait_for_timeout(100)
        combo = form_frame.get_by_role("combobox", name=combobox_name)
        if combo.count() > 0:
            combo.press_sequentially(value, delay=30)
        else:
            field.press_sequentially(value, delay=30)
        return True
    except Exception:
        return False


def _verify_contact_info(page: Page, test_data: dict) -> None:
    """Verify contact information is visible on the matter detail card."""
    angular_iframe = page.locator('iframe[title="angularjs"]')
    angular_iframe.wait_for(state="visible", timeout=15000)

    outer_iframe = page.frame_locator('iframe[title="angularjs"]')
    inner_iframe = outer_iframe.frame_locator('#vue_iframe_layout')

    name_locator = inner_iframe.get_by_text(test_data["full_name"])
    name_locator.first.wait_for(state="visible", timeout=10000)
    print(f"     [OK] Name visible: {test_data['full_name']}")

    email_locator = outer_iframe.get_by_text(test_data["email"])
    try:
        email_locator.first.wait_for(state="visible", timeout=5000)
        print(f"     [OK] Email visible: {test_data['email']}")
    except Exception:
        print(f"     [WARN] Email not visible on card (may be truncated)")

    phone_locator = outer_iframe.get_by_text(test_data["phone"])
    try:
        phone_locator.first.wait_for(state="visible", timeout=5000)
        print(f"     [OK] Phone visible: {test_data['phone']}")
    except Exception:
        print(f"     [WARN] Phone not visible on card (may be formatted differently)")


def test_create_matter(page: Page, context: dict) -> None:
    """
    Test: Create Matter via Quick Actions

    Creates a new matter (client/property/patient) using Quick Actions.
    Adapts to both full "Property" form and simpler "Client" form.

    Saves to context:
    - created_matter_name: The full name of the created matter
    - created_matter_email: The email of the created matter
    - created_matter_id: The ID extracted from the URL (for delete test)
    """
    test_data = generate_test_data()
    base_url = get_base_url(context)

    # ========== PART 1: Navigate to dashboard and open Add matter form ==========
    print("  Step 1: Ensuring we're on dashboard...")
    if "/app/dashboard" not in page.url:
        dashboard_link = page.get_by_text("Dashboard", exact=True)
        dashboard_link.click()
        page.wait_for_url("**/app/dashboard**", timeout=30000)
    page.wait_for_load_state("domcontentloaded")

    print("  Step 2: Opening Add matter form...")
    opened = _open_add_matter_via_dashboard_panel(page)
    if not opened:
        print("  [Fallback] Dashboard panel not found, using sidebar Quick Actions...")
        _open_add_matter_via_sidebar(page)

    # ========== PART 2: Wait for form to load ==========
    print("  Step 3: Waiting for form to load...")
    form_frame = _find_form_frame(page, timeout_ms=30000)
    if not form_frame:
        print("  DEBUG: Available frames:")
        for i, frame in enumerate(page.frames):
            url_preview = (frame.url[:50] + "...") if len(frame.url) > 50 else frame.url
            print(f"    [{i}] name='{frame.name}', url='{url_preview}'")
        raise Exception("Could not find form frame with 'First Name' field")

    form_frame.locator('text=First Name').wait_for(state='visible', timeout=15000)
    print("  Step 4: Form ready (First Name field visible).")

    # Click "Show more" if available (expands Referred by, Social media, etc.)
    show_more_btn = form_frame.get_by_role("button", name="Show more")
    has_show_more = False
    try:
        if show_more_btn.count() > 0:
            show_more_btn.click()
            page.wait_for_timeout(500)
            has_show_more = True
            print("  [OK] Clicked Show more")
    except Exception:
        pass

    # ========== PART 3: Fill Contact Information ==========
    print("  Step 5: Filling contact information...")

    first_name_field = form_frame.get_by_role("textbox", name="First Name *")
    first_name_field.click()
    first_name_field.press_sequentially(test_data["first_name"], delay=50)

    last_name_field = form_frame.get_by_role("textbox", name="Last Name")
    last_name_field.click()
    last_name_field.press_sequentially(test_data["last_name"], delay=50)

    _try_fill_combobox(form_frame, page, "Email", "Email", test_data["email"])

    _try_fill_combobox(form_frame, page, "Mobile phone", "Mobile phone", test_data["phone"]) or \
        _try_fill_combobox(form_frame, page, "Phone", "Phone", test_data["phone"])

    address_field = form_frame.get_by_label("Address").first
    try:
        if address_field.count() > 0:
            address_field.click()
            address_field.press_sequentially(test_data["contact_address"], delay=30)
    except Exception:
        pass

    if has_show_more:
        _try_fill_field(form_frame, "textbox", "Referred by", test_data["referred_by"], use_press=True)

    # ========== PART 4: Fill Matter Details (if available - Property form only) ==========
    print("  Step 6: Filling additional details (if available)...")

    matter_address_filled = False
    for entity in MATTER_ENTITY_NAMES:
        if _try_fill_field(form_frame, "textbox", f"{entity.capitalize()} address", test_data["matter_address"]):
            matter_address_filled = True
            break
    if not matter_address_filled:
        entity_pattern = "|".join([e.capitalize() for e in MATTER_ENTITY_NAMES])
        _try_fill_field(form_frame, "textbox",
                        re.compile(rf"({entity_pattern}) address", re.IGNORECASE),
                        test_data["matter_address"])

    _try_fill_field(form_frame, "textbox", "How can we help you?", test_data["help_request"])

    for entity in MATTER_ENTITY_NAMES:
        try:
            dropdown = form_frame.get_by_role("listbox", name=f"{entity.capitalize()} type")
            if dropdown.count() > 0:
                dropdown.click()
                option = form_frame.get_by_role("option", name=test_data["matter_type"])
                option.wait_for(state="visible", timeout=5000)
                option.click()
                page.wait_for_timeout(200)
                print(f"  [OK] Selected {entity} type: {test_data['matter_type']}")
                break
        except Exception:
            continue

    _try_fill_field(form_frame, "textbox", "Special instructions/requests", test_data["special_instructions"])

    notes_field = form_frame.get_by_role("textbox", name="Private notes")
    try:
        if notes_field.count() > 0:
            notes_field.click()
            notes_field.press_sequentially(test_data["private_notes"], delay=20)
    except Exception:
        pass

    # ========== PART 5: Save and Verify ==========
    print("  Step 7: Clicking Save...")
    save_btn = form_frame.get_by_role("button", name=re.compile(r"Save|SAVE", re.IGNORECASE))
    save_btn.click()

    page.wait_for_url(re.compile(r"/app/clients/"), timeout=30000)
    expect(page).to_have_url(re.compile(r"/app/clients/[a-z0-9]+"), timeout=30000)

    url = page.url
    matter_id_match = re.search(r'/app/clients/([^/]+)', url)
    matter_id = matter_id_match.group(1) if matter_id_match else None

    page.wait_for_load_state("domcontentloaded")

    print(f"  Step 8: Verifying created matter: {test_data['full_name']}...")
    expect(page).to_have_title(re.compile(re.escape(test_data["full_name"])), timeout=30000)

    # ========== PART 6: Verify Contact Information on Card ==========
    print("  Step 9: Verifying contact information on card...")
    _verify_contact_info(page, test_data)

    context["created_matter_name"] = test_data["full_name"]
    context["created_matter_email"] = test_data["email"]
    context["created_matter_id"] = matter_id

    print(f"  [OK] Created matter: {test_data['full_name']}")
    print(f"     Email: {test_data['email']}")
    print(f"     Phone: {test_data['phone']}")
    print(f"     Matter ID: {matter_id}")
